//! Code generators: the C header and the Lua schema, both derived from the
//! layout descriptors. `hsmp-tools gen-ipc` writes them; the `ipc-schema` gate check
//! regenerates and diffs them.
//! Generated files are never edited by hand.

use std::fmt::Write;

use crate::header::{ctr, RefuseCode, REFUSE_CODES};
use crate::layout::{IpcType, TypeDesc};
use crate::schema::{self, Dir, Form, CAPS, FLAGS, PODS};
use crate::segment::{Segment, LAYOUT_HASH, SEGMENT_SIZE};
use crate::{ABI_MAJOR, ABI_MINOR};

/// Repository-relative paths of the generated files.
pub const C_HEADER_PATH: &str = "crates/hsmp-native/cpp/gen/hsmp_ipc.h";
pub const LUA_SCHEMA_PATH: &str = "mods/shared/hsmp_ipc_schema.lua";

fn c_type(d: &TypeDesc) -> (String, String) {
    // (base type, array suffix)
    match d {
        TypeDesc::Prim { c, .. } => (c.to_string(), String::new()),
        TypeDesc::Struct { name, .. } => (format!("hsmp_{}", name), String::new()),
        TypeDesc::Array { elem, len } => {
            let (b, s) = c_type(elem);
            (b, format!("[{}]{}", len, s))
        }
        TypeDesc::Str { cap } => ("char".to_string(), format!("[{}]", cap)),
        TypeDesc::Bool => ("uint8_t".to_string(), String::new()),
    }
}

/// Every struct reachable from the record kinds, dependencies first, each once (by name;
/// the generic `VarBuf` / `Stamped` / `SeqSlot` wrappers are not records and are skipped).
fn record_structs() -> Vec<&'static TypeDesc> {
    fn visit(d: &'static TypeDesc, out: &mut Vec<&'static TypeDesc>) {
        match d {
            TypeDesc::Struct { name, fields, .. } => {
                if out.iter().any(|x| x.name() == *name) {
                    return;
                }
                for f in *fields {
                    visit(f.ty, out);
                }
                out.push(d);
            }
            TypeDesc::Array { elem, .. } => visit(elem, out),
            _ => {}
        }
    }
    let mut out = Vec::new();
    for r in schema::records() {
        visit(r.head, &mut out);
        if let Some(row) = r.row {
            visit(row, &mut out);
        }
    }
    out
}

/// A field name as a C / C++ identifier: a reserved word (e.g. `class`, a Lua / Rust field name
/// of the loadout records) gets a trailing `_` in the header only.
fn c_ident(n: &str) -> String {
    const RESERVED: &[&str] = &["class", "new", "delete", "template", "typename", "this", "operator", "private", "public",
        "protected", "virtual", "friend", "namespace", "using", "default", "register", "auto", "union", "signed", "unsigned",
        "char", "int", "float", "double", "long", "short", "bool", "static", "const", "volatile", "inline", "extern"];
    if RESERVED.contains(&n) { format!("{n}_") } else { n.to_string() }
}

fn emit_c_struct(o: &mut String, d: &TypeDesc) {
    if let TypeDesc::Struct { name, size, fields, .. } = d {
        let _ = writeln!(o, "typedef struct hsmp_{} {{", name);
        for f in *fields {
            let (b, s) = c_type(f.ty);
            let _ = writeln!(o, "    {} {}{};", b, c_ident(f.name), s);
        }
        let _ = writeln!(o, "}} hsmp_{};", name);
        let _ = writeln!(o, "HSMP_SA(sizeof(hsmp_{n}) == {s}, \"hsmp_{n} size\");", n = name, s = size);
        for f in *fields {
            let _ = writeln!(o, "HSMP_SA(offsetof(hsmp_{n}, {f}) == {off}, \"hsmp_{n}.{f} offset\");", n = name, f = c_ident(f.name), off = f.offset);
        }
        o.push('\n');
    }
}

fn upper(s: &str) -> String {
    s.to_ascii_uppercase()
}

fn walk_offsets(out: &mut String, prefix: &str, base: usize, d: &TypeDesc, depth: usize) {
    if depth > 6 {
        return;
    }
    match d {
        TypeDesc::Struct { fields, .. } => {
            for f in *fields {
                let path = if prefix.is_empty() { upper(f.name) } else { format!("{}_{}", prefix, upper(f.name)) };
                let off = base + f.offset;
                let _ = writeln!(out, "#define HSMP_OFF_{} 0x{:x}u", path, off);
                walk_offsets(out, &path, off, f.ty, depth + 1);
            }
        }
        TypeDesc::Array { elem, len } => {
            let _ = writeln!(out, "#define HSMP_STRIDE_{} 0x{:x}u", prefix, elem.size());
            let _ = writeln!(out, "#define HSMP_COUNT_{} {}u", prefix, len);
            // Describe element 0 only; element i is at base + i * stride.
            if let TypeDesc::Struct { .. } = elem {
                walk_offsets(out, &format!("{}_0", prefix), base, elem, depth + 1);
            }
        }
        TypeDesc::Prim { .. } | TypeDesc::Str { .. } | TypeDesc::Bool => {}
    }
}

/// The C header: POD structs with `static_assert`s on every size and offset, region offsets,
/// kinds, caps, flags, refuse codes and the layout hash.
pub fn c_header() -> String {
    let mut o = String::new();
    o.push_str("/* GENERATED by `hsmp-tools gen-ipc` from crates/hsmp-ipc. DO NOT EDIT. */\n");
    o.push_str("#pragma once\n#include <stdint.h>\n#include <stddef.h>\n#ifdef __cplusplus\n#define HSMP_SA static_assert\n#else\n#define HSMP_SA _Static_assert\n#endif\n\n");
    let _ = writeln!(o, "#define HSMP_IPC_ABI_MAJOR {}u", ABI_MAJOR);
    let _ = writeln!(o, "#define HSMP_IPC_ABI_MINOR {}u", ABI_MINOR);
    let _ = writeln!(o, "#define HSMP_IPC_LAYOUT_HASH 0x{:016x}ull", LAYOUT_HASH);
    let _ = writeln!(o, "#define HSMP_IPC_SEGMENT_SIZE 0x{:x}u\n", SEGMENT_SIZE);
    o.push_str("#pragma pack(push, 8)\n");
    let mut emitted: Vec<&str> = Vec::new();
    for d in PODS.iter().copied().chain(record_structs()) {
        if emitted.contains(&d.name()) {
            continue;
        }
        emitted.push(d.name());
        emit_c_struct(&mut o, d);
    }
    o.push_str("#pragma pack(pop)\n\n/* Records (protocol v6 kinds; the wire header is hsmp_WireHdr). */\n");
    for r in schema::records() {
        let _ = writeln!(o, "#define HSMP_REC_{} 0x{:04x}u /* {} */", upper(r.name), r.kind, r.layout);
        if r.max_rows > 0 {
            let _ = writeln!(o, "#define HSMP_REC_{}_MAX_ROWS {}u", upper(r.name), r.max_rows);
        }
    }
    o.push_str("\n/* Code tables. */\n");
    for e in schema::enums() {
        for (n, v) in e.values {
            let _ = writeln!(o, "#define HSMP_{}_{} {}u", upper(e.name), upper(n), v);
        }
    }
    o.push_str("\n/* Region and field offsets from the segment base. */\n");
    walk_offsets(&mut o, "", 0, &<Segment as IpcType>::DESC, 0);
    o.push_str("\n/* Kinds. */\n");
    for k in schema::kinds() {
        let _ = writeln!(o, "#define HSMP_K_{} 0x{:04x}u", upper(k.name), k.kind);
    }
    o.push_str("\n/* Capability bits. */\n");
    for (n, v) in CAPS {
        let _ = writeln!(o, "#define HSMP_CAP_{} 0x{:x}ull", n, v);
    }
    o.push_str("\n/* frame() flags. */\n");
    for (n, v) in FLAGS {
        let _ = writeln!(o, "#define HSMP_FLAG_{} 0x{:x}u", n, v);
    }
    o.push_str("\n/* Refuse codes. */\n");
    for c in REFUSE_CODES {
        let _ = writeln!(o, "#define HSMP_REFUSE_{} {}u", upper(c.as_str()), *c as u32);
    }
    o
}

fn lua_str(s: &str) -> String {
    let mut out = String::from("\"");
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn lua_type(d: &TypeDesc) -> String {
    match d {
        TypeDesc::Prim { name, .. } => lua_str(name),
        TypeDesc::Struct { name, .. } => lua_str(name),
        TypeDesc::Array { elem, len } => format!("{{ {}, {} }}", lua_type(elem), len),
        TypeDesc::Str { cap } => format!("{{ \"str\", {} }}", cap),
        TypeDesc::Bool => lua_str("bool"),
    }
}

fn flow_names(f: u8) -> String {
    let v: Vec<&str> = schema::flow::NAMES.iter().filter(|(_, b)| f & b != 0).map(|(n, _)| *n).collect();
    v.join(",")
}

/// The Lua schema module (`mods/shared/hsmp_ipc_schema.lua`): ABI, layout hash, kinds, caps,
/// flags, refuse codes, counter names and the field lists of every POD struct.
pub fn lua_schema() -> String {
    let mut o = String::new();
    o.push_str("-- GENERATED by `hsmp-tools gen-ipc` from crates/hsmp-ipc. DO NOT EDIT.\n");
    o.push_str("-- The facade (hsmp_ipc.lua) checks HSMPNative.abi() against ABI / LAYOUT_HASH at load.\n");
    o.push_str("local S = {}\n");
    let _ = writeln!(o, "S.ABI_MAJOR = {}\nS.ABI_MINOR = {}", ABI_MAJOR, ABI_MINOR);
    let _ = writeln!(o, "S.LAYOUT_HASH = \"{:016x}\"", LAYOUT_HASH);
    let _ = writeln!(o, "S.SEGMENT_SIZE = {}", SEGMENT_SIZE);
    o.push_str("\n-- kind name -> { id, cap, dir, form, replaces }\nS.KINDS = {\n");
    for k in schema::kinds() {
        let dir = match k.dir {
            Dir::GameToSidecar => "g2s",
            Dir::SidecarToGame => "s2g",
            Dir::Local => "local",
        };
        let form = match k.form {
            Form::Slot => "slot",
            Form::Bus => "bus",
            Form::PeerSlot => "peer_slot",
        };
        let _ = writeln!(
            o,
            "    {} = {{ id = 0x{:04x}, cap = 0x{:x}, dir = \"{}\", form = \"{}\", replaces = {} }},",
            k.name, k.kind, k.cap, dir, form, lua_str(k.replaces)
        );
    }
    o.push_str("}\nS.KIND_BY_ID = {}\nfor name, k in pairs(S.KINDS) do S.KIND_BY_ID[k.id] = name end\n\nS.CAPS = {\n");
    for (n, v) in CAPS {
        let _ = writeln!(o, "    {} = 0x{:x},", n, v);
    }
    o.push_str("}\n\nS.FLAGS = {\n");
    for (n, v) in FLAGS {
        let _ = writeln!(o, "    {} = 0x{:x},", n, v);
    }
    o.push_str("}\n\nS.REFUSE = {\n");
    for c in REFUSE_CODES {
        let _ = writeln!(o, "    [{}] = {},", *c as u32, lua_str(c.as_str()));
    }
    let _ = writeln!(o, "}}\nS.REFUSE_NONE = {}\n\nS.COUNTERS = {{", RefuseCode::None as u32);
    for n in ctr::NAMES {
        let _ = writeln!(o, "    {},", lua_str(n));
    }
    o.push_str("}\n\nS.PLAY_MODES = {");
    for (n, v) in schema::pose::PLAY_MODES {
        let _ = write!(o, " [{}] = {},", v, lua_str(n));
    }
    o.push_str(" }\n\n-- POD struct -> ordered { name, type } (type = scalar name, struct name, { elem, len } or { \"str\", cap })\nS.STRUCTS = {\n");
    let mut emitted: Vec<&str> = Vec::new();
    for d in PODS.iter().copied().chain(record_structs()) {
        if emitted.contains(&d.name()) {
            continue;
        }
        emitted.push(d.name());
        if let TypeDesc::Struct { name, size, fields, .. } = d {
            let _ = writeln!(o, "    {} = {{ size = {}, fields = {{", name, size);
            for f in *fields {
                let _ = writeln!(o, "        {{ {}, {} }},", lua_str(f.name), lua_type(f.ty));
            }
            o.push_str("    } },\n");
        }
    }
    o.push_str("}\n\n-- record name -> { id, layout, row, count, max_rows, cap, flow, chan }\nS.RECORDS = {\n");
    for r in schema::records() {
        let row = r.row.map_or("nil".to_string(), |d| lua_str(d.name()));
        let count = r.count_field.map_or("nil".to_string(), lua_str);
        let _ = writeln!(
            o,
            "    {} = {{ id = 0x{:04x}, layout = {}, row = {}, count = {}, max_rows = {}, cap = 0x{:x}, flow = {}, chan = {} }},",
            r.name, r.kind, lua_str(r.layout), row, count, r.max_rows, r.cap, lua_str(&flow_names(r.flow)), lua_str(r.chan.as_str())
        );
    }
    o.push_str("}\nS.RECORD_BY_ID = {}\nfor name, r in pairs(S.RECORDS) do S.RECORD_BY_ID[r.id] = name end\n\n-- slot name -> { record, form, dir, cap, world_scoped }\nS.SLOTS = {\n");
    for s in schema::slots() {
        let rec = schema::record_info(s.kind).map_or("?", |r| r.name);
        let form = match s.form {
            schema::SlotForm::Slot => "slot",
            schema::SlotForm::Blob => "blob",
            schema::SlotForm::PeerSlot => "peer_slot",
            schema::SlotForm::PeerBlob => "peer_blob",
            schema::SlotForm::Bus => "bus",
        };
        let dir = match s.dir {
            Dir::GameToSidecar => "g2s",
            Dir::SidecarToGame => "s2g",
            Dir::Local => "local",
        };
        let _ = writeln!(
            o,
            "    {} = {{ record = {}, form = \"{}\", dir = \"{}\", cap = 0x{:x}, world_scoped = {} }},",
            s.name, lua_str(rec), form, dir, s.cap, s.world_scoped
        );
    }
    o.push_str("}\n\n-- code tables: S.ENUMS.<table>.<NAME> = value, S.ENUM_NAMES.<table>[value] = NAME\nS.ENUMS, S.ENUM_NAMES = {}, {}\n");
    for e in schema::enums() {
        let _ = write!(o, "S.ENUMS.{} = {{", e.name);
        for (n, v) in e.values {
            let _ = write!(o, " {} = {},", n, v);
        }
        o.push_str(" }\n");
    }
    o.push_str("for t, vals in pairs(S.ENUMS) do\n    local names = {}\n    for n, v in pairs(vals) do names[v] = n end\n    S.ENUM_NAMES[t] = names\nend\n\nreturn S\n");
    o
}

/// Write both generated files under `repo_root`. Returns the paths written.
pub fn write_all(repo_root: &std::path::Path) -> std::io::Result<Vec<std::path::PathBuf>> {
    let mut written = Vec::new();
    for (rel, text) in [(C_HEADER_PATH, c_header()), (LUA_SCHEMA_PATH, lua_schema())] {
        let p = repo_root.join(rel);
        if let Some(d) = p.parent() {
            std::fs::create_dir_all(d)?;
        }
        std::fs::write(&p, text.replace("\r\n", "\n"))?;
        written.push(p);
    }
    Ok(written)
}

/// Compare the committed generated files under `repo_root` with fresh output. Returns the
/// relative paths that differ or are missing.
pub fn check_all(repo_root: &std::path::Path) -> Vec<&'static str> {
    let mut bad = Vec::new();
    for (rel, text) in [(C_HEADER_PATH, c_header()), (LUA_SCHEMA_PATH, lua_schema())] {
        let cur = std::fs::read_to_string(repo_root.join(rel)).unwrap_or_default().replace("\r\n", "\n");
        if cur != text {
            bad.push(rel);
        }
    }
    bad
}
