// generated by tools/ue4ss_pins -- do not edit
#pragma once
#define HSMP_UE4SS_GIT_SHA "e3ba1016"
#define HSMP_UE4SS_TIMESTAMP 0x6ABB88FAu
#define HSMP_UE4SS_SIZE_OF_IMAGE 0x013BA000u
#define HSMP_UE4SS_RVA_Gl 0x0134E450u /* size 48 */
#define HSMP_UE4SS_RVA_LuaLock 0x00C69E80u /* size 54 */
#define HSMP_UE4SS_RVA_LuaUnlock 0x00C69F20u /* size 14 */
#define HSMP_UE4SS_RVA_lua_pushcclosure 0x00C63BC0u /* size 173 */
// sizeof() of Lua 5.4 internals as compiled into UE4SS.dll (from its PDB)
#define HSMP_UE4SS_SIZEOF_lua_State 200u
#define HSMP_UE4SS_SIZEOF_global_State 1416u
#define HSMP_UE4SS_SIZEOF_CallInfo 64u
#define HSMP_UE4SS_SIZEOF_Table 56u
#define HSMP_UE4SS_SIZEOF_TString 32u
#define HSMP_UE4SS_SIZEOF_Udata 56u
#define HSMP_UE4SS_SIZEOF_CClosure 48u
#define HSMP_UE4SS_SIZEOF_LClosure 40u
#define HSMP_UE4SS_SIZEOF_Proto 128u
#define HSMP_UE4SS_SIZEOF_UpVal 40u
#define HSMP_UE4SS_SIZEOF_lua_Debug 136u
#define HSMP_UE4SS_SIZEOF_stringtable 16u
// Lua linkage inside UE4SS.dll: ue4ss_pins resolves `lua_pushcclosure` (above) as an
// unmangled C symbol in UE4SS.pdb, i.e. UE4SS compiled its Lua as C (LUA_COMPILED_AS_CPP
// off, errors are longjmps). Our private copy must match (hsmp_luauser.c checks it).
#define HSMP_UE4SS_LUA_COMPILED_AS_C 1
