name: Feature request
description: An idea for HSMP.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What would you like, and why?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you considered
