//! `hsmp-tools mapdump-summary [outDir]`: build `<outDir>/_summary.md`
//! (markdown tables) from MapDump's JSON output (port of tools/mapdump/summarize.py).
//! Default outDir: docs/arena_static.

use anyhow::{Context, Result};
use hsmp_tools::paths;
use hsmp_tools::pyfmt::{fixed, py_repr};
use serde_json::Value;
use std::collections::{BTreeMap, HashMap};
use std::path::{Path, PathBuf};

#[derive(clap::Args)]
pub struct Args {
    /// MapDump output dir (default: docs/arena_static)
    out: Option<PathBuf>,
}

const ARENAS: [&str; 7] = [
    "Map_Arena_Alley",
    "Map_Arena_Pit",
    "Map_Arena_Yard",
    "Map_Arena_Slums",
    "Map_Arena_Cellar",
    "Map_Arena_LordsHall",
    "Map_Arena_EastTower",
];

static NULL: Value = Value::Null;

fn load(p: &Path) -> Result<Value> {
    serde_json::from_str(&paths::read_text(p)?).with_context(|| format!("parse {}", p.display()))
}

fn get<'a>(v: &'a Value, k: &str) -> &'a Value {
    v.get(k).unwrap_or(&NULL)
}

fn truthy(v: &Value) -> bool {
    match v {
        Value::Null | Value::Bool(false) => false,
        Value::Number(n) => n.as_f64().map(|x| x != 0.0).unwrap_or(true),
        Value::String(s) => !s.is_empty(),
        Value::Array(a) => !a.is_empty(),
        Value::Object(o) => !o.is_empty(),
        _ => true,
    }
}

/// Python `str()` of a json value (scalars only matter here).
fn pstr(v: &Value) -> String {
    match v {
        Value::Null => "None".into(),
        Value::Bool(b) => if *b { "True" } else { "False" }.into(),
        Value::Number(n) => n.as_i64().map(|i| i.to_string()).unwrap_or_else(|| py_repr(n.as_f64().unwrap_or(0.0))),
        Value::String(s) => s.clone(),
        v => v.to_string(),
    }
}

fn s(v: &Value) -> &str {
    v.as_str().unwrap_or("")
}

fn list(v: &Value) -> &[Value] {
    v.as_array().map(|a| a.as_slice()).unwrap_or(&[])
}

fn len(v: &Value) -> usize {
    match v {
        Value::Array(a) => a.len(),
        Value::Object(o) => o.len(),
        Value::String(s) => s.chars().count(),
        _ => 0,
    }
}

fn last_seg(x: &str, sep: char) -> &str {
    x.rsplit(sep).next().unwrap_or("")
}

/// Counter -> (key, count) sorted by key.
fn counter(it: impl Iterator<Item = String>) -> BTreeMap<String, usize> {
    let mut m = BTreeMap::new();
    for k in it {
        *m.entry(k).or_insert(0) += 1;
    }
    m
}

pub fn run(a: Args) -> Result<i32> {
    let out = match a.out {
        Some(o) => o,
        None => paths::repo_root()?.join("docs").join("arena_static"),
    };
    let ce_path = out.join("_combat_events.json");
    let combat_events = if ce_path.exists() { load(&ce_path)? } else { Value::Object(Default::default()) };
    // map -> [(event name, combatants)]
    let mut events_by_map: HashMap<String, Vec<(String, Value)>> = HashMap::new();
    if let Value::Object(m) = &combat_events {
        for (name, ev) in m {
            if let Some(level) = ev.get("Level").and_then(|l| l.as_str()) {
                if !ev.is_object() {
                    continue;
                }
                let m = last_seg(level, '/').split('.').next().unwrap_or("").to_string();
                events_by_map.entry(m).or_default().push((name.clone(), get(ev, "Combatants Amount").clone()));
            }
        }
    }

    let mut lines: Vec<String> = vec!["# MapDump summary (generated by `hsmp-tools mapdump-summary`)".into(), "".into()];
    lines.extend(
        [
            "## Arena maps",
            "",
            "| Map | Combat events (base combatants) | Spawn points | Weapons | Destructibles | Traps | Fences | Containers | Light props | Levers/Chains | Movable/sim SMAs | Other | Runtime spawners |",
            "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
        ]
        .map(String::from),
    );
    let mut details: Vec<String> = vec![];
    let known = [
        "weapon",
        "quiver",
        "destructible",
        "trap",
        "fence",
        "container",
        "light_prop",
        "lever",
        "chain",
        "static_mesh_actor_movable",
    ];
    for m in ARENAS {
        let p = out.join(format!("{m}.json"));
        if !p.exists() {
            continue;
        }
        let d = load(&p)?;
        let wo = list(get(&d, "world_objects"));
        let c = counter(wo.iter().map(|o| pstr(get(o, "category"))));
        let cn = |k: &str| c.get(k).copied().unwrap_or(0);
        let other: usize = c.iter().filter(|(k, _)| !known.contains(&k.as_str())).map(|(_, v)| v).sum();
        let evs = events_by_map.get(m).map(|v| v.as_slice()).unwrap_or(&[]);
        let ev = evs.iter().map(|(n, a)| format!("{} ({})", n.replace("BP_CombatEvent_", ""), pstr(a))).collect::<Vec<_>>().join(", ");
        let ev = if ev.is_empty() { "-".to_string() } else { ev };
        let spawners =
            counter(list(get(&d, "spawners")).iter().map(|s| pstr(get(s, "class")))).into_keys().collect::<Vec<_>>().join(", ");
        let sps = list(get(&d, "spawn_points"));
        lines.push(format!(
            "| {m} | {ev} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {other} | {spawners} |",
            sps.len(),
            cn("weapon") + cn("quiver"),
            cn("destructible"),
            cn("trap"),
            cn("fence"),
            cn("container"),
            cn("light_prop"),
            cn("lever") + cn("chain"),
            cn("static_mesh_actor_movable")
        ));
        details.push("".into());
        details.push(format!("### {m}"));
        details.push("".into());
        details.push(format!(
            "Sources: {} packages; warnings: {}; errors: {}",
            len(get(&d, "sources")),
            len(get(&d, "warnings")),
            len(get(&d, "errors"))
        ));
        details.push("".into());
        details.push("| Spawn point | Location (x, y, z) | Yaw | Game modes | Combat modes | Play modes | Source |".into());
        details.push("|---|---|---|---|---|---|---|".into());
        let mut sorted: Vec<&Value> = sps.iter().collect();
        sorted.sort_by(|a, b| s(get(a, "name")).cmp(s(get(b, "name"))));
        for sp in sorted {
            let eff = get(sp, "effective_properties");
            let keys = |k: &str| -> String {
                let v = get(eff, k);
                let r = list(v)
                    .iter()
                    .filter(|x| x.is_object() && truthy(get(x, "Value")))
                    .map(|x| last_seg(s(get(x, "Key")), '(').trim_end_matches(')').to_string())
                    .collect::<Vec<_>>()
                    .join(", ");
                if r.is_empty() {
                    "-".into()
                } else {
                    r
                }
            };
            let loc = list(get(sp, "location")).iter().map(|v| fixed(v.as_f64().unwrap_or(0.0), 0)).collect::<Vec<_>>().join(", ");
            let src = last_seg(s(get(sp, "source")), '/');
            details.push(format!(
                "| {} | ({loc}) | {} | {} | {} | {} | {src} |",
                s(get(sp, "name")),
                fixed(get(get(sp, "rotation"), "yaw").as_f64().unwrap_or(0.0), 1),
                keys("Works in these Game Modes"),
                keys("Works in these Combat Modes"),
                keys("Works in these Play Modes")
            ));
        }
        let cls = counter(
            wo.iter().filter(|o| s(get(o, "category")) != "static_mesh_actor_movable").map(|o| pstr(get(o, "class"))),
        );
        details.push("".into());
        details.push(format!(
            "World-object classes: {}",
            cls.iter().map(|(k, v)| format!("{k} x{v}")).collect::<Vec<_>>().join(", ")
        ));
        let by_via = counter(wo.iter().map(|o| {
            let v = get(o, "via");
            let v = if truthy(v) { pstr(v) } else { "persistent".to_string() };
            v.split(' ').next().unwrap_or("").to_string()
        }));
        details.push("".into());
        details.push(format!(
            "World objects by origin: {}",
            by_via.iter().map(|(k, v)| format!("{k}: {v}")).collect::<Vec<_>>().join(", ")
        ));
    }
    lines.extend(details);

    let idx_path = out.join("_index.json");
    if idx_path.exists() {
        let idx = load(&idx_path)?;
        lines.extend(
            [
                "",
                "## All maps index",
                "",
                "| Map | Kind | Status | Spawn pts | World objs | Pulled in by | Referenced by (non-map assets) | Flags |",
                "|---|---|---|---|---|---|---|---|",
            ]
            .map(String::from),
        );
        for e in list(&idx) {
            let name = s(get(e, "map"));
            let mut flags: Vec<String> = vec![];
            if ARENAS.contains(&name) {
                flags.push("arena".into());
            }
            if let Some(evs) = events_by_map.get(name).filter(|v| !v.is_empty()) {
                flags.push(format!(
                    "combat-event: {}",
                    evs.iter().map(|(n, _)| n.replace("BP_CombatEvent_", "")).collect::<Vec<_>>().join("/")
                ));
            }
            if name.to_lowercase().contains("test") {
                flags.push("test-named".into());
            }
            let kind = s(get(e, "kind"));
            if kind != "sublevel"
                && kind != "level_instance"
                && !truthy(get(e, "pulled_in_by"))
                && !truthy(get(e, "referenced_by_assets"))
            {
                flags.push("UNREFERENCED (likely unused/dev)".into());
            }
            if name == "Entry" {
                flags.push("engine default map".into());
            }
            if name.starts_with("Abyss") && get(e, "world_objects").as_f64().unwrap_or(0.0) < 5.0 {
                flags.push("near-empty stub".into());
            }
            let refs = list(get(e, "referenced_by_assets"));
            let mut refs_s = refs.iter().take(4).map(|r| last_seg(s(r), '/').to_string()).collect::<Vec<_>>().join(", ");
            if refs.len() > 4 {
                refs_s += &format!(" (+{})", refs.len() - 4);
            }
            let pulled = list(get(e, "pulled_in_by")).iter().map(pstr).collect::<Vec<_>>().join(", ");
            let or_dash = |x: String| if x.is_empty() { "-".to_string() } else { x };
            lines.push(format!(
                "| {name} | {kind} | {} | {} | {} | {} | {} | {} |",
                pstr(get(e, "parse_status")),
                pstr(get(e, "spawn_points")),
                pstr(get(e, "world_objects")),
                or_dash(pulled),
                or_dash(refs_s),
                or_dash(flags.join("; "))
            ));
        }
    }
    let dst = out.join("_summary.md");
    std::fs::write(&dst, lines.join("\n") + "\n").with_context(|| format!("write {}", dst.display()))?;
    println!("wrote {}", dst.display());
    Ok(0)
}
